### ISSUE TITLE
German umlauts are returned incorrectly

### ISSUE THREAD

**Issue by OliverSteinau** [ArtifexSoftware/MuPDF.NET#92] opened 2024-06-20 15:00 UTC
When extracting text from a PDF page, German umlauts are not returned correctly: eg. "ü" is returned as "Ã¼" -- it seems UTF8 text is not correctly converted to UTF16.
PyMuPDF does not have this issue.
I attached a PDF containing umlauts as an example.

[test-umlaut.pdf](https://github.com/user-attachments/files/15915968/test-umlaut.pdf)

**Comment by JorjMcKie** [comment] 2024-06-20 16:50
Thank you for this submission and your interest in MuPDF.NET.

This is a known issue.
Caused by C# strings being encoded as UTF-16, whereas MuPDF always accepts and delivers UTF8.
We are currently working on a general solution.

**Comment by greendreamer** [comment] 2024-06-28 18:15
Fixed with MuPDF.NET version 2.0.9-alpha

**Closed by greendreamer** 2024-06-28 18:15 UTC
